Proyecto Final/EDUNICA/Models/Leccion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUNICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leccion
    {
        public int Id { get; set; }
        public string NombreLeccion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Completado { get; set; }
        public int CursoId { get; set; }
        public int ProgresoId { get; set; }
        public string Img { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Progreso Progreso { get; set; }
    }
}

Proyecto Final/EDUNICA/Controllers/LeccionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EDUNICA.Models;

namespace EDUNICA.Controllers
{
    [Authorize]
    public class LeccionsController : Controller
    {
        private DiagramaEDUNICAContainer db = new DiagramaEDUNICAContainer();

        // GET: Leccions
        public ActionResult Index(int ? id)
        {
            var lecciones = db.Lecciones.Include(l => l.Curso).Include(l => l.Progreso).Where( l=> l.CursoId == id);
            return View(lecciones.ToList());
        }

        // GET: Leccions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leccion leccion = db.Lecciones.Find(id);
            if (leccion == null)
            {
                return HttpNotFound();
            }
            return View(leccion);
        }

        // GET: Leccions/Create
        public ActionResult Create()
        {
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "NombreCurso");
            ViewBag.ProgresoId = new SelectList(db.Progresos, "Id", "Cantidad");
            return View();
        }

        // POST: Leccions/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NombreLeccion,Descripcion,Completado,CursoId,ProgresoId,Img")] Leccion leccion)
        {
            if (ModelState.IsValid)
            {
                db.Lecciones.Add(leccion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "NombreCurso", leccion.CursoId);
            ViewBag.ProgresoId = new SelectList(db.Progresos, "Id", "Cantidad", leccion.ProgresoId);
            return View(leccion);
        }

        // GET: Leccions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leccion leccion = db.Lecciones.Find(id);
            if (leccion == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "NombreCurso", leccion.CursoId);
            ViewBag.ProgresoId = new SelectList(db.Progresos, "Id", "Cantidad", leccion.ProgresoId);
            return RedirectToAction("Index", "Cursoes");

        }

        // POST: Leccions/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NombreLeccion,Descripcion,Completado,CursoId,ProgresoId,Img")] Leccion leccion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leccion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "NombreCurso", leccion.CursoId);
            ViewBag.ProgresoId = new SelectList(db.Progresos, "Id", "Id", leccion.ProgresoId);
            return RedirectToAction("Index","Cursoes");
        }

        // GET: Leccions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leccion leccion = db.Lecciones.Find(id);
            if (leccion == null)
            {
                return HttpNotFound();
            }
            return View(leccion);
        }

        // POST: Leccions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Leccion leccion = db.Lecciones.Find(id);
            db.Lecciones.Remove(leccion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto Final/EDUNICA/Views/Leccions/Create.cshtml
@model EDUNICA.Models.Leccion

@{
    ViewBag.Title = "Create";
}
<style>
    .nose{
        width:100%;
        margin:20px;
    }
    .form-horizontal{
        padding:40px;
    }
</style>
@using (Html.BeginForm("Create", "Leccions", FormMethod.Post, new { enctype = "multipart/form-data", id = "XD" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h3>Crear un Nueva Leccion</h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    <div class="form-group">
        <div class="col-md-10">
            <div class="container-img" style="display:flex; justify-content:center; width:100%; padding:20px; margin-left:1rem;">
                <img src="" alt="XD" id="imgview" style="width:150px; border-radius:30px;" />

            </div>
            <input type="file" id="inputFile" name="InputFile" value="" class="form-control" accept="image/*">
        </div>
    </div>
    @Html.LabelFor(model => model.NombreLeccion, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.NombreLeccion, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NombreLeccion, "", new { @class = "text-danger" })
    </div>
</div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Completado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-select" aria-label="Default select example" name="Completado">
                <option selected>Seleccione un Estado</option>
                <option value="true">Completado</option>
                <option value="false">No Completado</option>
            </select>
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CursoId, "Curso", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CursoId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CursoId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProgresoId, "Progreso", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProgresoId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CursoId, "", new { @class = "text-danger" })
        </div>
    </div>


    <input type="hidden" name="Img" id="Imgxd" />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear Leccion" class="nose" />
        </div>
    </div>
</div>
}


<script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/10.6.0/firebase-app.js";
    import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.6.0/firebase-storage.js";

    const firebaseConfig = {
        apiKey: "",
        authDomain: "",
        projectId: "",
        storageBucket: "",
        messagingSenderId: "",
        appId: "",
        measurementId: ""
    };


    const app = initializeApp(firebaseConfig);
    const storage = getStorage(app);

    document.addEventListener('DOMContentLoaded', function () {
        const inputFile = document.getElementById('inputFile'); // Reemplaza 'inputFile' con el ID real de tu campo de archivo

        inputFile.addEventListener('change', function (event) {
            event.preventDefault(); // Evita el comportamiento predeterminado del campo de archivo

            subirImagenYCrearLeccion();
        });
    });

    function subirImagenYCrearLeccion() {
        const fileInput = document.getElementById('inputFile');

        if (fileInput.files.length > 0) {
           // alert("Probando");
            const file = fileInput.files[0];
            //alert(file);
            const storageRef = ref(storage, `ImgLeccion/${file.name}`);
            // Subir la imagen a Firebase Storage
            uploadBytes(storageRef, file).then(snapshot => {
               // alert('Imagen subida con éxito');
                return getDownloadURL(snapshot.ref);
            }).then(downloadURL => {

               // alert(downloadURL);
                let vaxd = document.getElementById("Imgxd");
                vaxd.value = downloadURL;
                var img = document.getElementById("imgview");
                img.src = downloadURL;
                fileInput.value = downloadURL;

            });


        } else {
            console.error('Selecciona una imagen');
        }

      
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto Final/EDUNICA/Views/Leccions/Delete.cshtml
@model EDUNICA.Models.Leccion

@{
    ViewBag.Title = "Delete";
}

<style>
    #cdelete {
        align-items: center;
        text-align: center;
        padding: 20px;
    }

    .footer {
        position: relative;
        top: 10.7rem;
    }

    .containerxd {
        display: flex;
        justify-content: center;
        position: relative;
        top: 5rem;
    }

    .nose:hover {
        background-color: red;
    }
</style>
<div class="containerxd">
    <div class="card" id="cdelete">
        <svg xmlns="http://www.w3.org/2000/svg" width="46" height="46" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
            <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
        </svg>
        <h2>Eliminar</h2>
        <hr />
        <div class="card-body">
            <h3>¿Está Seguro de Querer Eliminar La Leccion @Model.NombreLeccion?</h3>
            <p>Esta Acción no se puede deshacer</p>
        </div>
        <div class="container">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="opti">
                    <input type="submit" value="Eliminar" class="nose" />
                    @Html.ActionLink("Volver a Inicio", "Index")
                </div>
            }
        </div>
    </div>
</div>

Proyecto Final/EDUNICA/Views/Leccions/Details.cshtml
@model EDUNICA.Models.Leccion

@{
    ViewBag.Title = "Details";
}

<style>
    .contenedor, .card-img{
        width:100%;
    }
    .card-img {
        width: 100%;
        height: 60vh;
        background-color: #00008b96;
        background-image: url( @Model.Img );
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        filter: blur(23px);
    }
    .img {
        width: 300px;
        border-radius: 5%;
        position: relative;
        z-index: 9999;
        left: 33rem;
        bottom: 18rem;
    }
    .let {
        letter-spacing:0.2em;
        z-index: 999;
        position: relative;
        color: black;
        font-size: xx-large;
        left: 54rem;
        top:1rem;
    }
</style>
<div class="contenedor">
    <span class="let">@Model.Curso.NombreCurso</span>
    <div class="card-img">
    </div>
    <img src="@Model.Img" alt="Img" class="img" />
    <div style="text-align:center; position:relative; bottom:16rem;">
        <ul style="list-style:none;">
            <li><h1>@Model.NombreLeccion</h1></li>
            <li><p>@Model.Descripcion</p></li>
            <li>Progreso: @Model.Progreso.Cantidad %</li>
        </ul>
    </div>
</div>
@if (User.IsInRole("admin") && User.IsInRole("profesor"))
{
    <p class="opti">
        @Html.ActionLink("Editar", "Edit", new { id = Model.Id })
        @Html.ActionLink("Volver", "Index", new { id = Model.CursoId })
    </p>
}

Proyecto Final/EDUNICA/Views/Leccions/Edit.cshtml
@model EDUNICA.Models.Leccion

@{
    ViewBag.Title = "Editar";
}
<style>
    .nose {
        width: 100%;
        margin: 10px;
    }

    .form-horizontal {
        margin: 40px;
    }
</style>


<h2 style="text-decoration-line: underline;text-align: center;padding: 10px;">
    Editando Leccion - @Model.NombreLeccion <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001" />
    </svg>
</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <div class="col-md-10">
            <div class="container-img" style="display:flex; justify-content:center; width:100%; padding:20px; margin-left:1rem;">
                <img src="@Model.Img" alt="XD" id="imgview" style="width:150px; border-radius:30px;" />

            </div>
            <input type="file" id="inputFile" name="InputFile" value=""  class="form-control" accept="image/*">
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NombreLeccion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NombreLeccion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NombreLeccion, "", new { @class = "text-danger" })
        </div>
    </div>


    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="form-floating">
        <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 200px; width:700px;" name="Descripcion">@Model.Descripcion</textarea>

    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Completado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Completado, new SelectList(
                new List<Object>{
                    new { value = true , text = "Completado"  },
                    new { value = false , text = "No Completado" }
                },
                "value",
                "text",
                Model.Completado
            ), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Completado, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CursoId, "CursoId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CursoId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CursoId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProgresoId, "ProgresoId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProgresoId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProgresoId, "", new { @class = "text-danger" })
        </div>
    </div>

  
    <input type="hidden" name="Img" id="Imgxd" />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar Cambios" class="nose" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/10.6.0/firebase-app.js";
    import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.6.0/firebase-storage.js";

    const firebaseConfig = {
        apiKey: "",
        authDomain: "",
        projectId: "",
        storageBucket: "",
        messagingSenderId: "",
        appId: "",
        measurementId: ""
    };


    const app = initializeApp(firebaseConfig);
    const storage = getStorage(app);

    document.addEventListener('DOMContentLoaded', function () {
        const inputFile = document.getElementById('inputFile'); // Reemplaza 'inputFile' con el ID real de tu campo de archivo

        inputFile.addEventListener('change', function (event) {
            event.preventDefault(); // Evita el comportamiento predeterminado del campo de archivo

            subirImagenYCrearLeccion();
        });
    });

    function subirImagenYCrearLeccion() {
        const fileInput = document.getElementById('inputFile');

        if (fileInput.files.length > 0) {
            //alert("Probando");
            const file = fileInput.files[0];
            //alert(file);
            const storageRef = ref(storage, `ImgLeccion/${file.name}`);
            // Subir la imagen a Firebase Storage
            uploadBytes(storageRef, file).then(snapshot => {
                //alert('Imagen subida con éxito');
                return getDownloadURL(snapshot.ref);
            }).then(downloadURL => {

                //alert(downloadURL);
                let vaxd = document.getElementById("Imgxd");
                vaxd.value = downloadURL;
                var img = document.getElementById("imgview");
                img.src = downloadURL;
                fileInput.value = downloadURL;

            });


        } else {
            console.error('Selecciona una imagen');
        }


    }
</script>

Proyecto Final/EDUNICA/Views/Leccions/Index.cshtml
@model IEnumerable<EDUNICA.Models.Leccion>

@{
    ViewBag.Title = "Lecciones";
}

<style>
    .card-footer > a , .xdd > a {
        text-decoration: none;
        font-size: 1.2rem;
        background-color: darkblue;
        border-radius: 30px;
        margin: 10px;
    }
    .card-footer > a{
        width:100px;
    }
    .xdd > a {
        color: white;
    }
    .lection {
        display:grid; grid-template-columns:1fr 1fr 1fr;
        place-items:normal;
    }
    #xdx:hover {
        font-size: 1.3rem;
        padding: 20px;
    }
    #xdx {
        width: 300px;
        height: 460px;
    }
</style>

<div class="container-md">
    <div class="xdd" style="display:flex; justify-content:space-between;">
        <h2 style="text-align:center;">Lecciones</h2>
        @if (User.IsInRole("admin") || User.IsInRole("profesor"))
         {
              @Html.ActionLink("+ Leccion", "Create", null, new { @class = "btn btn-info" })
         }

    </div>
<hr />
<div class="lection">
    @foreach (var item in Model)
    {


        <div class="card m-sm-3" id="xdx" style="-webkit-box-shadow: 5px 7px 18px -3px rgba(49,58,232,1); -moz-box-shadow: 5px 7px 18px -3px rgba(49,58,232,1); box-shadow: 5px 7px 18px -3px rgba(49,58,232,1); width:310px; cursor:pointer; padding:10px;">
            <div class="form-check form-switch" id="xd">
                <input type="checkbox" name="Completado" id="chex" class="form-check-input" @if (item.Completado is true) { <text> checked</text> } />
            </div>
            <div class="card-imgx" style="display:flex; justify-content:center;">
                <img src="@item.Img" alt="LeccionImg" style="width:100%; height:200px; border-radius:30px;" />
            </div>
            <div class="card-body">
                <ul style="list-style:none;">
                    <li><h2>@item.NombreLeccion</h2></li>
                    <li>
                        <p>@item.Curso.NombreCurso</p>
                    </li>
                </ul>
            </div>
            @if (User.IsInRole("admin") || User.IsInRole("profesor"))
            {
                <div class="card-footer" style="display:flex; justify-content:space-between; align-items:center; text-align:center;">
                    @Html.ActionLink("✏️", "Edit", new { id = item.Id })
                    @Html.ActionLink("📑", "Details", new { id = item.Id })
                    @Html.ActionLink("🗑️", "Delete", new { id = item.Id })
                </div>
            }
            @if (User.IsInRole("alumno"))
            {
                <div class="card-footer" style="display:flex; justify-content:center; align-items:center; text-align:center;">
                    @Html.ActionLink("📑", "Details", new { id = item.Id })
                </div>
            }

        </div>
    }
    </div>
</div>